version: 2.1

orbs:
  android: circleci/android@0.2.1


references:
  gem_key: &gems_key
             gems-{{ checksum "Gemfile.lock" }}
  restore_gems_cache: &restore_gems_cache
    restore_cache:
      key: *gems_key

  save_gems_cache: &save_gems_cache
    save_cache:
      key: *gems_key
      paths:
        - vendor/bundle

  ruby_dependencies: &ruby_dependencies
    run:
      name: Download Ruby Dependencies
      command: |
        gem install bundler
        bundle check || bundle install --path vendor/bundle

  android_dependencies: &android_dependencies
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies

  decode_android_key: &decode_android_key
    run:
      name: Decode Android key store
      command: echo $KEYSTORE | base64 -di | tee keystore.jks app/keystore.jks >/dev/null

  create_google_play_key: &create_google_play_key
    run:
      name: Create Google Play Key
      command: echo $GOOGLE_PLAY_KEY | base64 -d | tee google-play-key.json app/google-play-key.json > /dev/null

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - run:
          command: ./gradlew build

  unit-test:
    executor: android/android
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: ./gradlew test
  deploy-alpha:
    executor: android/android
    steps:
      - checkout
      - *restore_gems_cache
      - *ruby_dependencies
      - *decode_android_key
      - *android_dependencies
      - *save_gems_cache
      - *create_google_play_key
      - run:
          name: Run Deploy to alpha
          command: bundle exec fastlane alpha
  deploy-prod:
    executor: android/android
    steps:
      - checkout
      - *restore_gems_cache
      - *ruby_dependencies
      - *decode_android_key
      - *android_dependencies
      - *save_gems_cache
      - *create_google_play_key
      - run:
          name: Run Deploy to prod
          command: bundle exec fastlane prod

workflows:
  version: 2.1
  run-unit-tests:
    jobs:
      - unit-test:
          filters:
            branches:
              only: feijao
      - build:
          filters:
            branches:
              only: feijao

  run-deploy-alpha:
    jobs:
      - unit-test
      - deploy-alpha:
          requires:
            - unit-test

  run-deploy-prod:
    jobs:
      - unit-test
      - deploy-alpha:
          requires:
            - unit-test
      - holder:
          type: approval
          requires:
            - unit-test
            - deploy-alpha
      - deploy-prod:
          requires:
            - unit-test
            - deploy-alpha
            - holder
