version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  run-test:
    executor: android/android
    steps:
      - checkout
      - run:
          command: ./gradlew build

workflows:
  test-run:
    jobs:
      - run-test:
        filters:
          branches:
            only:
              - feijao1