version: 2.1

orbs:
 android: circleci/android@0.2.1

jobs:
  first-filter:
    executor: android/android
    steps:
      - checkout
      - run:
          command: ./gradlew build

workflows:
  first-filter:
    jobs:
      - first-filter:
        filters:
          branches:
            only:
              - master