version: 2.1

orbs:
  android: circleci/android@0.2.1

references:
  gem_key: &gems_key
             gems-{{ checksum "Gemfile.lock" }}
  restore_gems_cache: &restore_gems_cache
    restore_cache:
      key: *gems_key

  save_gems_cache: &save_gems_cache
    save_cache:
      key: *gems_key
      paths:
        - vendor/bundle

  ruby_dependencies: &ruby_dependencies
    run:
      name: Download Ruby Dependencies
      command: |
        gem install bundler
        bundle check || bundle install --path vendor/bundle
  android_dependencies: &android_dependencies
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies

  decode_android_key: &decode_android_key
    run:
      name: Decode Android key store
      command: echo $KEYSTORE | base64 -di | tee keystore.jks app/keystore.jks >/dev/null

  create_google_play_key: &create_google_play_key
    run:
      name: Create Google Play Key
      command: echo $GOOGLE_PLAY_KEY | base64 -d | tee google-play-key.json app/google-play-key.json > /dev/null
jobs:
  test-unit:
    executor: android/android
    steps:
      - checkout
      - run:
          command: ./gradlew build

  test-deploy:
    executor: android/android
    steps:
      - checkout
      - *restore_gems_cache
      - *ruby_dependencies
      - *decode_android_key
      - *android_dependencies
      - *save_gems_cache
      - *create_google_play_key
      - run:
          name: Deploy to Play Store
          command: bundle exec fastlane alpha

workflows:
  version: 2.1
  unit-tests:
    jobs:
      - test-unit:
        filters:
          branches:
            only: cachorro
  teste_and_deploy:
    jobs:
      - test-unit
      - hold:
          type: approval
          requires:
            - test-unit
      - test-deploy:
          requires:
            - hold
          filters:
            branches:
              only: cachorro


