version: 2.1

orbs:
  android: circleci/android@0.2.1


references:
  only_run_build: &only_run_build
    run:
      name: Only run Build
      command: ./gradlew build

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - *only_run_build
      - run:
          command: ./gradlew build

  unit-test:
    executor: android/android
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: ./gradlew test

workflows:
  version: 2.1
  run-unit-tests:
    jobs:
      - unit-test:
          filters:
            branches:
              only: master
      - build:
          filters:
            branches:
              only: master
